### PR TITLE
Finalize the branch for publication

### PR DESCRIPTION
**Pull request by LinguList**
@fractaldragonflies, please see what I have been doing here.

1. Adding CONTRIBUTORS.md with our names (I forgot your John *E*, you may want to add that).
2. Fixing one Line that prevents using concepticon v3.0.0, by just pulling the Concepticon Gloss labels from Concepticon and not from WOLD or IDS.
3. Adjusting the NOTES.md which appears in README.md after runnin cldfbench lexibank.makecldf. 
4. Modifying metadata.json, which now gives our EACL paper as the "how to quote the dataset", which I find okay.
5. Adding sources for IDS and WOLD. For WOLD, we add the WOLD itself and Miller2020, since this provides the orthoprofile for WOLD, and for IDS we add Miller2023 (the new EACL paper) as it provides orthoprofiles for Spanish.

### CODE REVIEW

**Comment by LinguList** [comment]
Note that in this form, we can easily make a version 1.0, and this version will then be automatically uploaded to Zenodo, where we get a DOI, and with this DOI we can then reference the data in the paper (no zips for ACL, only links to Archives!).

**Comment by LinguList** [comment]
I tested how everything runs, and it is fine. I suggest you also test one more time. It is anyway fast.

**Comment by LinguList** [comment]
If the Markov branch is not really important for the paper, I'd leave it out for now, and rather link this with Zenodo (which I'll do, once you tell me it is good to go) and rather concentrate on adding a few more lines to the paper. All initial ideas, you could MENTION them there, and then, you'd be the one who has articulated them first, which is probably useful.

**Comment by fractaldragonflies** [comment]
> I tested how everything runs, and it is fine. I suggest you also test one more time. It is anyway fast.

I will test out in this final form... just to be sure there are no surprises in my environment.  Of course using a virtual environment.

**Comment by fractaldragonflies** [comment]
> If the Markov branch is not really important for the paper, I'd leave it out for now, and rather link this with Zenodo (which I'll do, once you tell me it is good to go) and rather concentrate on adding a few more lines to the paper. All initial ideas, you could MENTION them there, and then, you'd be the one who has articulated them first, which is probably useful.

Let's wait to integrate the Markov Chain stuff.  I  put a mention in the updated paper as a footnote to conclusion. Not sure if that is really 'acceptable' for conference paper, but it was a way to avoid having to write into methods section, include in software, and add new results stuff, when already at 5 page updated paper limit.

**Comment by fractaldragonflies** [comment]
Testing install.  

- Tried using the makevirtualenv command, but not unknown command. Did an install of virtualenvwrapper, but still no go, so something a bit more complicated.  Left aside and use my conda commands.
- Haven't merged yet, so copied down zip of 'final' and renamed to sabor.  I ignored git checkout v1.0 command for now.
- Install OK, and download OK.
- Fails on makecldf due to reference to glottolog and concepticon databases. Here is message.
```
(testsabor) johnmiller@Johns-M1-Fractal-Dragon sabor % cldfbench lexibank.makecldf lexibank_sabor.py --glottolog=../glottolog --concepticon=../concepticon-data --clts=../clts --glottolog-version=v4.7 --concepticon-version=v3.0.0 --clts-version=v2.2.0

Error initializing catalog glottolog
invalid repository path: ../glottolog
```

Hmm... I had previously (2 years ago?) installed with 'catconfig', but at application support level for johnmiller. cldfbench knows where to look for the catalog and pulls in the appropriate files.

OK.  I'll modify command for my test for now in order to verify that the app does function.

Seems we would need to install these databases if

**Comment by fractaldragonflies** [comment]
> @fractaldragonflies, please see what I have been doing here.
> 
> 1. Adding CONTRIBUTORS.md with our names (I forgot your John _E_, you may want to add that).
> 2. Fixing one Line that prevents using concepticon v3.0.0, by just pulling the Concepticon Gloss labels from Concepticon and not from WOLD or IDS.
> 3. Adjusting the NOTES.md which appears in README.md after runnin cldfbench lexibank.makecldf.
> 4. Modifying metadata.json, which now gives our EACL paper as the "how to quote the dataset", which I find okay.
> 5. Adding sources for IDS and WOLD. For WOLD, we add the WOLD itself and Miller2020, since this provides the orthoprofile for WOLD, and for IDS we add Miller2023 (the new EACL paper) as it provides orthoprofiles for Spanish.

VERY Pretty...  looks professional!

**Comment by LinguList** [comment]
Sorry, this was written without checking against it: please replace (!) glottolog/concepticon/clts by x-repos, so `--glottolog-repos`, `--concepticon-repos`, `--clts-repos`.

**Comment by LinguList** [comment]
This is also described in `cldfbench --help`.

**Comment by fractaldragonflies** [comment]
Using my `conda` commands, and **with the exception** of  `git checkout v1.0` command, this install works fine after installing repositories one directory above the installed sabor directory.  Links to Glottolog, Concepticon, CLTS work fine.  I may not have paid attention to previously to your detail instructions on using this command!

I haven't installed the necessary path info to get the `mkvirtualenv` command work.  But I assume that professionals that use other `env` tools will be able to figure it our.

**WRT** specifying v1.0, what do we need to add?  [setup.py needs to be updated to this version.  But there must be something in the git database itself?]

On my mac, install of glottolog, clts, concepticon files is made automatically to application support directory just by using `cldfbench catconfig`.  Quite convenient as I avoid multiple copies of databases and `makecldf` command doesn't even need to refer to repositories.  Very cool.  And easy to update too.

**Comment by LinguList** [comment]
To make a version 1.0, I need to first link this repository with Zenodo (via our Zenodo account) and then, we do a release on git, where we specify the version. This is what we need now. If you think we are good to go, I'd do that tomorrow.

**Pull request merged**
